version: '3.4'

services:
  api:
    build:
      context: .
    expose:
      - 5000
    links:
      - database
      - cache
    depends_on:
      - database
      - cache

  database:
    image: mongo
    container_name: mongo
    command: mongod --port 27018
    ports:
      - 27018:27018

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:4000

  cache:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
