version: '3.4'

services:
  api:
    build:
      target: prod
    logging: 
      driver: none

  api-tests:
    build:
      context: ./test/cluster
    container_name: api-tests
    depends_on:
      - api

  database:
    logging: 
      driver: none
  
  nginx:
    logging: 
      driver: none

  cache:
    logging: 
      driver: none